### ISSUE TITLE
Main Thread continues to run when slave dies

### ISSUE THREAD

**Issue by jmashore** [Linch1/Web3TokenCharting#18]
Hello - First, thank you for your contribution. It's nice to see something that actually runs.

I've run this in the following environments: Windows10, Windows WSL Ubuntu, and a dedicated Ubuntu Server. Windows and Dedicated Ubuntu runs will with the exception of the issue I'm reporting. WSL Ubuntu has some issues with mongo connections. 

The problem I'm reporting occurs both in Windows10 and in the dedicated Ubuntu server environment.

When running the scraper, the slave (I assume) will occasionally throw an error and the slave will die, but the main thread continues to run and just keeps displaying "Main Price xxxxxx.xxxxx" over and over. No other messages are displayed.

When the slave dies, a stack trace is displayed, but as I said, the main thread knows nothing about it.  I would think the main thread needs to either monitor the slave with some kind of heartbeat and restart it if it dies, or if the slave dies the whole thing dies. I'd much rather it just restart the slave automagically. I've included the stack trace for your review :

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
Node Version 12.16.2
Full Node On Chainstack : Will provide credentials for testing if needed.

[SCRAPED BLOCK][OLD][CB] 20613920 0
(node:1459182) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/export/home/exchange/wsock_server/WeChartWeb3/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (/export/home/exchange/wsock_server/WeChartWeb3/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/export/home/exchange/wsock_server/WeChartWeb3/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/export/home/exchange/wsock_server/WeChartWeb3/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/export/home/exchange/wsock_server/WeChartWeb3/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/export/home/exchange/wsock_server/WeChartWeb3/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketOnEnd (_http_client.js:460:9)
    at TLSSocket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1459182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1459182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thank you again for your hard work and contribution

**Comment by jmashore** [comment]
I adjusted the package.json to this 👍  "scraper": "node  --unhandled-rejections=strict ./workers/updater/master.js"
Apparently, there is another error thrown early on that I was missing and it appears to be thrown every time I start. It does not stop the system and apparently SLAVE 0 continues to work, I'm just not sure it's working correctly.

I've added a log of the issue to this report. 
[log.txt](https://github.com/Linch1/WeChartWeb3/files/9388191/log.txt)

**Comment by Linch1** [comment]
Hello, thanks for reporting this, will look into it as soon as I can :+1:

**Comment by Linch1** [comment]
@jmashore by the way I forgot to mention the `restarter.js`, if you see in the pacakge.json there is also the script

`"restarter": "node ./workers/updater/restarter.js",`

if you run it also, it will restart automatically the slave when it dies. 
How to run it is mentioned in the `readme` :+1:
