### ISSUE TITLE
TypeError: Cannot read property 'ws_provider' of undefined

### ISSUE THREAD

**Issue by Nosok1503** [Linch1/Web3TokenCharting#26]
When I trying run, error arises. P.S. I install full-node provider https://github.com/self-node-official and it run successfully, also I do all Setup steps, ws and http URL added
 node --version  v12.22.12
npm --version 6.14.16
Can you help me?

npm run scraper

> pancakeswap-token-charting@1.0.0 scraper /root/WeChartWeb3
> node ./workers/updater/master.js

WARNING: NODE_ENV value of 'staging' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/root/WeChartWeb3/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/root/WeChartWeb3/workers/lib/web3.js:6
web3_wss.setProvider(new Web3.providers.WebsocketProvider( scraperConfig[process.env.CHAIN_ID].ws_provider ));
                                                                                               ^

TypeError: Cannot read property 'ws_provider' of undefined
    at Object.<anonymous> (/root/WeChartWeb3/workers/lib/web3.js:6:96)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/WeChartWeb3/workers/lib/block.listner.js:1:33)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/WeChartWeb3/workers/lib/scrape.block.stream.js:17:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pancakeswap-token-charting@1.0.0 scraper: `node ./workers/updater/master.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pancakeswap-token-charting@1.0.0 scraper script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-14T10_45_38_579Z-debug.log

![Screenshot_1](https://user-images.githubusercontent.com/61502708/207575885-feb47361-dcd1-4edb-9334-4a5f95dfd647.png)
![image](https://user-images.githubusercontent.com/61502708/207585735-10badef8-ad4f-4013-9cb6-f36031feba94.png)

**Comment by Linch1** [comment]
have you created also the .env from the .env.example inside the repo?
it seems that process.env.CHAIN_ID ( used inside workers/lib/web3.js ) is missing

**Comment by Nosok1503** [comment]
yes, i copy it
![image](https://user-images.githubusercontent.com/61502708/207595851-17267182-060b-4b26-94c9-8bc8727d512f.png)

**Comment by Nosok1503** [comment]
Some more information
![image](https://user-images.githubusercontent.com/61502708/207599140-7e87aa38-e02a-4733-ada0-60a5d6978350.png)
![image](https://user-images.githubusercontent.com/61502708/207599319-a8b11e40-6c15-451f-905d-60f2653972c7.png)
![image](https://user-images.githubusercontent.com/61502708/207599436-9e29af12-0c1d-400c-bd87-e41e1b762fcc.png)

**Comment by Nosok1503** [comment]
I recreate project and now have this error
![image](https://user-images.githubusercontent.com/61502708/207600411-ba92fd7c-6331-4008-92c4-ef83464468be.png)

**Comment by Linch1** [comment]
Which version of node are you using ? The `?.` syntax should be aviable in most recent versions

**Comment by Nosok1503** [comment]
node --version v12.22.12
npm --version 6.14.16

**Comment by Nosok1503** [comment]
update to 14 help

**Comment by Nosok1503** [comment]
I update my node version and right now have this type of error
![image](https://user-images.githubusercontent.com/61502708/207900613-988e7f69-8fc6-407e-b945-593944bad737.png)

**Comment by Nosok1503** [comment]
What node version you use?

**Comment by Nosok1503** [comment]
![image](https://user-images.githubusercontent.com/61502708/207908277-c55e55ff-fdbf-47b0-85dc-59c1d3b42602.png)
![image](https://user-images.githubusercontent.com/61502708/207908636-07955ccb-aa3d-48e1-81da-37a87475ec54.png)![image](https://user-images.githubusercontent.com/61502708/207908495-81914fcc-0e19-4d25-89d4-8c9f091d5366.png)
